# Generated by Django 3.2.8 on 2021-10-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='etc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='play',
            name='image',
            field=models.ImageField(null=True, upload_to='producer/'),
        ),
        migrations.AddField(
            model_name='play',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='ganre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
