# Generated by Django 3.2.8 on 2021-10-07 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producerapp', '0002_auto_20211007_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='play',
            old_name='ganre',
            new_name='genre',
        ),
    ]
