# Generated by Django 3.2.8 on 2021-10-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_playlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.AddField(
            model_name='profile',
            name='play1_rate',
            field=models.IntegerField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='play1_title',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='play2_rate',
            field=models.IntegerField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='play2_title',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
