# Generated by Django 3.2.8 on 2021-10-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_auto_20211007_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nickname',
            new_name='play3_title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='message',
        ),
        migrations.AddField(
            model_name='profile',
            name='play3_rate',
            field=models.IntegerField(max_length=1, null=True),
        ),
    ]
