# Generated by Django 3.2.8 on 2021-10-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('genre', models.CharField(max_length=200, null=True)),
                ('area', models.CharField(max_length=200, null=True)),
                ('rate', models.IntegerField(max_length=2, null=True)),
                ('vote', models.IntegerField(max_length=10, null=True)),
            ],
        ),
    ]
