# Generated by Django 3.2.8 on 2021-10-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlistapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='play',
            old_name='genre',
            new_name='genres',
        ),
    ]
