# Generated by Django 3.2.8 on 2021-10-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistapp', '0002_rename_genre_play_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='rate',
            field=models.FloatField(max_length=2, null=True),
        ),
    ]
