# Generated by Django 3.2.8 on 2021-10-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistapp', '0003_alter_play_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='rate',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
