# Generated by Django 3.2.8 on 2021-10-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistapp', '0004_alter_play_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='vote',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
